Repository FastCampus-MoReturn/Final-Project-FE, pull requests merged in 2023-04, with the labels that each got.

#25 Feat: 토스트 모달 스타일링, 옵션 추가
  src/apis/auth.ts
  src/main.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: Medium, Category: HTML&CSS

#27 feat : */pdf 경로에 실제 API로 pdf 전송 기능 추가
  .eslintrc.json
  package-lock.json
  package.json
  src/components/pdf-send/PDFComp.tsx
  src/components/pdf-send/Progress.tsx
  src/routes/Router.tsx
  vite.config.ts
Labels: Stats: Available, Priority: High, Type: Enhancement, Category: JS

#28 feat : fix modal
  src/contexts/modalContext.tsx
Labels: Stats: Available, Priority: Medium, Type: Maintenance, Category: JS

#29 Feat: ContentsBox 컴포넌트 생성 및 Pdf 해석 페이지 생성
  src/components/common/ContentsBox.tsx
  src/pages/PdfCommentary2.tsx
  src/routes/Router.tsx
Labels: Status: Completed, Priority: Medium, Category: HTML&CSS, Category: JS

#30 fear PDF 데이터 리덕스로 저장
  .eslintrc.json
  index.html
  package-lock.json
  package.json
  src/components/pdf-send/PDFComp.tsx
  src/pages/PdfSend.tsx
  src/store/hooks.ts
  src/store/pdfSlice.ts
  src/store/store.ts
  src/styles/DesignSystem.tsx
  src/styles/GlobalStyle.tsx
  src/styles/colors.ts
Labels: Stats: Available, Priority: Medium, Type: Maintenance, Category: JS

#31 용어사전 컴포넌트 분리 및 마크업 마무리
  index.html
  src/components/dictionary/defaultInfo.tsx
  src/components/dictionary/resultinfo.tsx
  src/components/dictionary/toggleInfo.tsx
  src/pages/Dictionary.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: Medium, Category: HTML&CSS, Category: JS

#32 feat: 임시로 explanation 페이지(등기부등본 해설 내용) 추가
  .eslintrc.json
  src/App.tsx
  src/assets/candy.png
  src/assets/excla.png
  src/components/Sidebar.tsx
  src/components/explanation/CheckList.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/components/pdf-send/PDFComp.tsx
  src/components/ui/ModalPortal.tsx
  src/contexts/modalContext.tsx
  src/pages/Explanation.tsx
  src/pages/NotFound.tsx
  src/routes/Router.tsx
Labels: Stats: Available, Status: In Progress, Priority: Medium, Category: HTML&CSS, Category: JS

#33 Feat: header,footer 마크업
  src/assets/footer-logo.svg
  src/assets/logo.svg
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
Labels: Priority: Medium, Category: HTML&CSS

#34 feat : pdf 응답 성공 시 step (페이지 이동)
  package-lock.json
  package.json
  src/apis/auth.ts
  src/assets/arrow.svg
  src/assets/caution_circle_36px.svg
  src/assets/check_24px.svg
  src/assets/check_circle_36px.svg
  src/assets/close_circle_36px.svg
  src/assets/file_upload_100px.svg
  src/assets/page_img.svg
  src/assets/pdf_72px.svg
  src/components/layout/Header.tsx
  src/components/pdf-send/PDFComp.tsx
  src/components/pdf-send/Progress.tsx
  src/components/pdf-send/step01/PDFInputIntro.tsx
  src/components/pdf-send/step02/PDFComp.tsx
  src/components/pdf-send/step02/PDFSendModule.tsx
  src/components/pdf-send/step02/dragEvent.ts
  src/pages/PdfSend.tsx
  src/pages/PdfStep.tsx
  src/routes/Router.tsx
  src/store/pdfSlice.ts
  src/styles/DesignSystem.tsx
  src/styles/GlobalStyle.tsx
Labels: Stats: Available, Priority: High, Type: Enhancement, Category: JS

#36 Feature : PDF 해석 페이지 실거래가 그래프 및 필터 제작
  package-lock.json
  package.json
  src/assets/img/areaVoca.png
  src/components/Commentary/AdditionalFeatures.tsx
  src/components/Commentary/BarChart.tsx
  src/components/Commentary/CustomSelect.tsx
  src/components/Commentary/InfoCheck.tsx
  src/components/Commentary/ValuationChartContainer.tsx
  src/components/Commentary/ValuationCheck.tsx
  src/pages/PdfCommentary2.tsx
Labels: Priority: High, Category: HTML&CSS, Category: JS

#37 feat : 서버 요청 에러처리 , 버튼들 인터렉션 추가 및 스타일 모듈화 , 스탭 로딩 컴포넌트 적용
  src/assets/check_circle_36px.svg
  src/components/pdf-send/CheckIcon.tsx
  src/components/pdf-send/StepProgress.tsx
  src/components/pdf-send/step01/PDFInputIntro.tsx
  src/components/pdf-send/step02/PDFSendModule.tsx
  src/components/pdf-send/step02/Progress.tsx
  src/components/pdf-send/step02/dragEvent.ts
  src/pages/PdfSend.tsx
  src/pages/PdfStep.tsx
  src/routes/Router.tsx
  src/styles/DesignSystem.tsx
  src/styles/GlobalStyle.tsx
Labels: Stats: Available, Priority: High, Type: Enhancement, Category: JS

#38 Feat: 용어사전 API 연동
  src/components/dictionary/resultinfo.tsx
Labels: Priority: Medium, Category: HTML&CSS, Category: JS

#39 Fix: api 수정에 따른 검색 기능 수정
  src/components/dictionary/resultinfo.tsx
Labels: Priority: Medium, Category: HTML&CSS, Category: JS

#40 Feature/transaction
  index.html
  src/App.tsx
  src/apis/auth.ts
  src/apis/instance.ts
  src/components/Commentary/AdditionalFeatures.tsx
  src/components/Commentary/BarChart.tsx
  src/components/Commentary/CustomSelect.tsx
  src/components/Commentary/InfoCheck.tsx
  src/components/Commentary/ValuationChartContainer.tsx
  src/components/Commentary/ValuationCheck.tsx
  src/components/Sidebar.tsx
  src/components/common/ContentsBox.tsx
  src/components/explanation/CheckList.tsx
  src/constants/routes.ts
  src/pages/Explanation.tsx
  src/pages/PdfCommentary2.tsx
  src/pages/PdfStep.tsx
  src/routes/Router.tsx
Labels: Priority: High, Category: HTML&CSS, Category: JS

#41 Fix: 홈 수정
  src/routes/Router.tsx
Labels: Priority: Low, Category: JS

#42 fix : 이미지 경로 수정, 라우터 경로 수정
  public/img/areaVoca.png
  src/components/Commentary/InfoCheck.tsx
  src/components/pdf-send/step02/PDFSendModule.tsx
  src/routes/Router.tsx
Labels: Stats: Available, Priority: Medium, Type: Maintenance, Category: JS

#43 Feature/transaction
  src/components/Commentary/BarChart.tsx
  src/components/Commentary/ValuationChartContainer.tsx
Labels: Priority: Medium, Category: HTML&CSS, Category: JS
