Repository FastCampus-MoReturn/Final-Project-FE, pull requests merged in 2023-03, with the labels that each got.

#2 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/기능-정의.md
Labels: Type: Maintenance, Category: Docs

#3 Feature/lint
  .editorconfig
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .prettierrc
  README.md
  package-lock.json
  package.json
  src/App.tsx
  src/apis/auth.ts
  src/apis/instance.ts
  src/constants/apiUrls.ts
  src/constants/routes.ts
  src/main.tsx
  src/routes/Router.tsx
  src/store/store.ts
  src/styles/GlobalStyle.tsx
  src/styles/colors.ts
Labels: Stats: Available, Priority: High, Type: Maintenance, Category: Test

#5 pdf 전송 모듈
  .eslintrc.json
  .gitignore
  README.md
  package-lock.json
  package.json
  src/components/Progress.tsx
  src/interfaces/user.ts
  src/pages/PdfSend.tsx
  src/routes/Router.tsx
Labels: Stats: Available, Priority: High, Type: Enhancement, Category: Test

#7 Feat: 카카오맵 구현 및 페이지 리디렉션 구현
  index.html
  package-lock.json
  package.json
  src/index.css
  src/pages/Commentary.tsx
  src/routes/Router.tsx
  tsconfig.json
Labels: Status: In Progress, Priority: High, Category: JS

#9 Feat: ComfirmModal 생성
  src/App.tsx
  src/components/ConfirmModal.tsx
  src/pages/NotFound.tsx
  src/store/modalSlice.ts
  src/store/store.ts
Labels: Stats: Available, Status: In Progress, Priority: Medium, Category: JS

#12 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Priority: Medium, Type: Question, Category: Docs

#16 Feat: Commentary 페이지 제작 및 마크업
  src/pages/Commentary.tsx
  src/pages/CommentaryTest.tsx
Labels: Status: In Progress, Priority: High, Category: HTML&CSS, Category: JS

#19 pdf design 적용
  src/components/pdf-send/PDFInput.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: Stats: Available, Priority: Medium, Type: Maintenance, Category: JS

#21 feat:Create Sidebar-component
  src/App.tsx
  src/components/Sidebar.tsx
Labels: Stats: Available, Status: In Progress, Priority: Medium, Category: HTML&CSS

#23 Feat: react-toastify 라이브러리 설치 및 테스트
  package-lock.json
  package.json
  src/apis/auth.ts
  src/main.tsx
  src/pages/NotFound.tsx
  tsconfig.json
Labels: Stats: Available, Priority: Medium, Category: JS

#24 Feat: 등기부등본 정보확인 페이지 마크업
  src/pages/InfoCheckPage.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: Medium, Category: HTML&CSS
